const RESEND_API_KEY = process.env.RESEND_API_KEY;
const PROJECT_DOCS_URL = process.env.PROJECT_DOCS_URL;
const PROJECT_SHEETS_URL = process.env.PROJECT_SHEETS_URL;

export { RESEND_API_KEY, PROJECT_DOCS_URL, PROJECT_SHEETS_URL };
